### PR TITLE
update of Greek (el) translation

### PR DESCRIPTION
**Pull request by nikoss**

### CODE REVIEW

**Comment by LiMinggang** [comment]
Manually updated with your latest work. Thanks!
Changed one string:
#: ../src/MadOptionsDialog.cpp:298
msgid "Record caret movements"
msgstr ""
"Καταγραφή των μετακινήσεων της περισπωμένης στο κατάστιχο των αναιρέσεων"

There are some new added string for new functions:
#: ../src/MadEditFrame.cpp:2137
msgid "Go Back"
msgstr ""

#: ../src/MadEditFrame.cpp:2137
msgid "Moves the caret to the previous location in the Selection History"
msgstr ""

#: ../src/MadEditFrame.cpp:2137
msgid "Go Back(Alt-,)"
msgstr ""

#: ../src/MadEditFrame.cpp:2138
msgid "Go Forward"
msgstr ""

#: ../src/MadEditFrame.cpp:2138
msgid "Moves the caret to the next location in the Selection History"
msgstr ""

#: ../src/MadEditFrame.cpp:2138
msgid "Go Forward(Alt-.)"
msgstr ""


Please help and this might be 0.4.4

**Comment by nikoss** [comment]
I have some problems with github.
I tried a few things, but they didn't work.
I think I'll end up deleting my fork of madedit-mod and creating a new one.
But I don't think that is worth it, for just a few strings.
Anyway, always, some strings are left untranslated.
Personally, I am more than happy if 90% of the strings are translated.

So, I will wait a while before I make a new update of the Greek translation.
Until then...

**Comment by LiMinggang** [comment]
No problem. You may only send me the el.po. It's OK. I can easily merge it
manually.

**Comment by LiMinggang** [comment]
0.4.4 is out with your latest translation but has some issue to upload it
to SF. The website has been in issues.

**Comment by LiMinggang** [comment]
Hi, Nikoss, are you still willing to help on the greek translation of MadEdit? 0.4.8 is incoming soon. Will include your translation if possible.

**Comment by nikoss** [comment]
I already have spell checking working under Mageia. If I remember correctly, I had installed the Greek package of hunspell (but it might have been any other of these ***spell systems). Maybe the dictionary you mention is useful for Madedit-Mod inside Microsoft Windows.

**Comment by LiMinggang** [comment]
That's fine

**Comment by LiMinggang** [comment]
Hi, Nikoss,
I've done coding for 0.4.9 which is mainly a bug fix/maintenance release(Fix IPC issue under Linux)  and introduced several new words for translation. Would you please help me to translate them to Greek.

Thanks!

**Comment by nikoss** [comment]
Ok, now, the way I work with translations is that, when I finish a translation, I save its version as 001, 002, 003, etc.
The git system has a different philosophy. It seems it is better to maintain a single branch.
So, I closed the other pull requests, and uploaded the latest translation in my "master" branch.
This is the "good" pull request.

**Comment by LiMinggang** [comment]
I found these two while manually merging yours. Would you please confirm if they were correct or not? If correct. I can apply them to the latest translation.

image

**Comment by nikoss** [comment]
> I found these two while manually merging yours.

I skipped them, because I didn't understand the meaning.
Now, that I read them again, I get it.
And no, the translations are not correct.
But you could make these sentences a bit more clear, by adding commas.
Because there are a lot of adjectives, you see...

Maybe...
```
Add braces to unbraced, one line, conditional statements.
Add one line braces to unbraced, one line, conditional statements.
```

See also:
[Commas with Paired Adjectives](http://englishplus.com/grammar/00000072.htm)

**Comment by LiMinggang** [comment]
"unbraced one line conditional statements" is something like below:
if( a > 100 && b < 4500 || c != 0 && d> 1500 ) e = a + c +b +d;

brace is '{' and '}' in C/C++.

"conditional statement" is:
if( a < 100 ) a = a + 100
else a = a-100

**Comment by nikoss** [comment]
Ok, I just translated the 2 remaining strings.

**Comment by LiMinggang** [comment]
Everything looks good!

**Comment by LiMinggang** [comment]
I've merged all to my branch. Will close the pull request.

**Pull request closed without merging**
