### PR TITLE
Greek translation 006

### PR DESCRIPTION
**Pull request by nikoss**

### CODE REVIEW

**Comment by nikoss** [comment]
Newer translation available.

**Comment by nikoss** [comment]
> Do you want a preview build for verifying translation? If did, please tell me what Linux you are using. Mageia 5 X64?

I use Mageia 6, x64. 
A preview build would be useful, mainly, for checking if it installs, and runs, properly.
But if you don't have the time, no need to go to all that trouble.
I will check it when the "normal" rpm comes out.

**Comment by LiMinggang** [comment]
Not a big duel. I'll update my VM of Mageia while preparing different builds.

**Comment by LiMinggang** [comment]
Hi, nikoss, would you please update the Greek translation based on the latest po file? 0.4.10 is on the edge. And did you meet the issue #241 on Magiea?

**Comment by nikoss** [comment]
Unfortunately, I am kind of busy these days. I 'll have to skip this update. Maybe, in a couple of months, I will start maintaining the translations, again.

As for issue #241 , I use IceWM on my Mageia, and don't have such a problem.

**Comment by LiMinggang** [comment]
No problem.

**Pull request closed without merging**
